### ISSUE TITLE
Need to style the the ndt test client

### ISSUE THREAD

**Issue by willscott** [codeforseattle/seanetmap#3]
the current one has weird fonts, and should integrate more cleanly.

**Comment by JohnTigue** [comment]
I think what willscott is saying here is that something got lost when the NDT JS-client code demo got dragged into SEANetMap.

The original demo can be seen running at:
http://files.opentechinstitute.org/~critzo/mlab/examples/ndt-javascript-client/examples/d3_circle/

Nicer fonts, as test progresses the circle changes colors counter-clockwise. These are probably CSS things. Dunno.

**Comment by YonasBerhe** [comment]
I think the fonts now are fine. The only problem with the current one is the missing progress bar.

**Comment by YonasBerhe** [comment]
Got the status bar up and running.

**Comment by JohnTigue** [comment]
Thanks. Much better. That where we were, which was a step back from what M-Lab gave us.

I liked the monochrome look you had going at Civic Hack Night. Now that all the original parts of which the testers UI consists are in the mix, as Scott was saying we need to UX that. 

I really have no idea where to put it. Maybe it could become part of that opening dialogs. But modal dialogs are a faux pas in general so that might just be the wrong road.

Some how is should be along the lines of:
1. there is unobtrusive but obvious "Start test" UI.
2. User clicks start test and the circle appears (or grows in radius, perhaps centering on screen; it is D3 so that would be easy and slick)
3. Test completes and stats are shown.
4. user dismisses results

5. Bonus: as they dismiss the circle recedes into their identified region of the map?
